# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#
# kube-jenkins-imager e2e test
#
# VERSION 0.0.1
FROM google/cloud-sdk

MAINTAINER Evan Brown <evanbrown@google.com>

RUN gcloud components update alpha --quiet
COPY . /tmp/kube-jenkins-imager
RUN cp /tmp/kube-jenkins-imager/ssl_secrets.template.json /tmp/kube-jenkins-imager/ssl_secrets.json
WORKDIR /tmp/kube-jenkins-imager

ENTRYPOINT ["test/e2e.sh"]
